/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  ScreenRecorderPlugin: () => ScreenRecorderPlugin,
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");
var import_path = require("path");

// src/desktop-capture.ts
var import_obsidian = require("obsidian");
async function captureDesktopWithElectron(app, options, warnings) {
  const electron = require("electron");
  const remote = electron.remote;
  const session = safely(() => {
    var _a;
    return (_a = remote == null ? void 0 : remote.getCurrentWebContents) == null ? void 0 : _a.call(remote).session;
  });
  if (!(session == null ? void 0 : session.setDisplayMediaRequestHandler)) {
    throw new Error(
      "\u5F53\u524D Obsidian \u684C\u9762\u73AF\u5883\u672A\u5F00\u653E\u5C4F\u5E55\u6355\u83B7\u63A5\u53E3\uFF0C\u8BF7\u66F4\u65B0 Obsidian \u684C\u9762\u5B89\u88C5\u7A0B\u5E8F"
    );
  }
  const includeLoopbackAudio = options.enableSystemAudio && process.platform === "win32";
  if (options.enableSystemAudio && !includeLoopbackAudio) {
    warnings.push(
      "\u5F53\u524D macOS \u684C\u9762\u6355\u83B7\u6A21\u5F0F\u4E0D\u652F\u6301\u7CFB\u7EDF\u97F3\u9891\uFF0C\u5C06\u7EE7\u7EED\u5F55\u5236\u5C4F\u5E55\u548C\u9EA6\u514B\u98CE"
    );
  }
  let handlerInstalled = false;
  let handlerFailure = null;
  let handlerTask = null;
  try {
    session.setDisplayMediaRequestHandler((_request, callback) => {
      handlerTask = (async () => {
        try {
          const sources = await readDesktopSources(electron, remote);
          const selected = await chooseDesktopSource(app, sources);
          const response = {
            video: selected.source
          };
          if (includeLoopbackAudio) {
            response.audio = "loopback";
          }
          callback(response);
        } catch (error) {
          handlerFailure = error;
          callback({});
        }
      })();
    }, {
      useSystemPicker: process.platform === "darwin"
    });
    handlerInstalled = true;
    try {
      return await navigator.mediaDevices.getDisplayMedia({
        video: {
          frameRate: {
            ideal: options.frameRate,
            max: options.frameRate
          },
          cursor: options.showCursor ? "always" : "never"
        },
        audio: includeLoopbackAudio
      });
    } catch (error) {
      if (handlerTask) {
        await handlerTask;
      }
      if (handlerFailure) {
        throw handlerFailure;
      }
      throw error;
    }
  } finally {
    if (handlerInstalled) {
      try {
        session.setDisplayMediaRequestHandler(null);
      } catch (error) {
        console.warn(
          "Screen Recorder: failed to reset display media handler",
          error
        );
      }
    }
  }
}
async function readDesktopSources(electron, remote) {
  const candidates = getDesktopCapturerCandidates(electron, remote);
  if (candidates.length === 0) {
    throw new Error(
      "\u5F53\u524D Obsidian \u684C\u9762\u73AF\u5883\u672A\u5F00\u653E\u7A97\u53E3\u5217\u8868\u63A5\u53E3\uFF0C\u8BF7\u66F4\u65B0 Obsidian \u684C\u9762\u5B89\u88C5\u7A0B\u5E8F"
    );
  }
  const permissionBefore = getScreenAccessStatus(electron, remote);
  if (process.platform === "darwin" && (permissionBefore === "denied" || permissionBefore === "restricted")) {
    throw createScreenPermissionError(permissionBefore);
  }
  const failures = [];
  for (const candidate of candidates) {
    for (const thumbnailSize of [
      { width: 384, height: 216 },
      { width: 0, height: 0 }
    ]) {
      try {
        const sources = await candidate.capturer.getSources({
          types: ["screen", "window"],
          thumbnailSize,
          fetchWindowIcons: false
        });
        if (sources.length > 0) {
          return sources;
        }
        failures.push(`${candidate.label}: \u672A\u8FD4\u56DE\u5C4F\u5E55\u6216\u7A97\u53E3`);
      } catch (error) {
        failures.push(
          `${candidate.label}: ${describeError(error)}`
        );
      }
    }
  }
  const permissionAfter = getScreenAccessStatus(electron, remote);
  console.warn(
    "Screen Recorder: failed to enumerate desktop sources",
    {
      permissionBefore,
      permissionAfter,
      failures
    }
  );
  if (process.platform === "darwin" && permissionAfter !== "granted") {
    throw createScreenPermissionError(permissionAfter);
  }
  throw new Error(
    `Obsidian \u65E0\u6CD5\u8BFB\u53D6\u5C4F\u5E55\u548C\u7A97\u53E3\u5217\u8868\uFF08${failures.join("\uFF1B")}\uFF09\u3002\u8BF7\u5B8C\u5168\u9000\u51FA\u5E76\u91CD\u65B0\u6253\u5F00 Obsidian \u540E\u518D\u8BD5`
  );
}
function getDesktopCapturerCandidates(electron, remote) {
  const candidates = [
    toCapturerCandidate(
      "remote.getBuiltin",
      safely(
        () => {
          var _a;
          return (_a = remote == null ? void 0 : remote.getBuiltin) == null ? void 0 : _a.call(
            remote,
            "desktopCapturer"
          );
        }
      )
    ),
    toCapturerCandidate(
      "remote.desktopCapturer",
      safely(() => remote == null ? void 0 : remote.desktopCapturer)
    ),
    toCapturerCandidate(
      "remote.require",
      safely(
        () => {
          var _a;
          return (_a = remote == null ? void 0 : remote.require) == null ? void 0 : _a.call(remote, "electron").desktopCapturer;
        }
      )
    ),
    toCapturerCandidate(
      "electron.desktopCapturer",
      safely(() => electron.desktopCapturer)
    )
  ];
  const uniqueCapturers = /* @__PURE__ */ new Set();
  return candidates.filter(
    (candidate) => {
      if (!candidate || uniqueCapturers.has(candidate.capturer)) {
        return false;
      }
      uniqueCapturers.add(candidate.capturer);
      return true;
    }
  );
}
function toCapturerCandidate(label, capturer) {
  if (!(capturer == null ? void 0 : capturer.getSources)) {
    return null;
  }
  return { label, capturer };
}
function getScreenAccessStatus(electron, remote) {
  var _a, _b, _c, _d;
  const preferences = (_c = (_b = (_a = safely(
    () => {
      var _a2;
      return (_a2 = remote == null ? void 0 : remote.getBuiltin) == null ? void 0 : _a2.call(
        remote,
        "systemPreferences"
      );
    }
  )) != null ? _a : safely(() => remote == null ? void 0 : remote.systemPreferences)) != null ? _b : safely(
    () => {
      var _a2;
      return (_a2 = remote == null ? void 0 : remote.require) == null ? void 0 : _a2.call(remote, "electron").systemPreferences;
    }
  )) != null ? _c : safely(() => electron.systemPreferences);
  return (_d = safely(() => {
    var _a2;
    return (_a2 = preferences == null ? void 0 : preferences.getMediaAccessStatus) == null ? void 0 : _a2.call(preferences, "screen");
  })) != null ? _d : "unknown";
}
function createScreenPermissionError(status) {
  const statusText = status === "not-determined" ? "\u5C1A\u672A\u6388\u6743" : status === "denied" ? "\u5DF2\u62D2\u7EDD" : status === "restricted" ? "\u53D7\u5230\u7CFB\u7EDF\u9650\u5236" : "\u72B6\u6001\u672A\u77E5";
  return new Error(
    `macOS \u5C4F\u5E55\u5F55\u5236\u6743\u9650${statusText}\u3002\u8BF7\u6253\u5F00\u201C\u7CFB\u7EDF\u8BBE\u7F6E \u2192 \u9690\u79C1\u4E0E\u5B89\u5168\u6027 \u2192 \u5C4F\u5E55\u4E0E\u7CFB\u7EDF\u97F3\u9891\u5F55\u5236\u201D\uFF0C\u5141\u8BB8 Obsidian\uFF0C\u7136\u540E\u5B8C\u5168\u9000\u51FA\u5E76\u91CD\u65B0\u6253\u5F00 Obsidian`
  );
}
function safely(read) {
  try {
    return read();
  } catch (e) {
    return void 0;
  }
}
function chooseDesktopSource(app, sources) {
  const options = sources.map((source) => ({
    source,
    kind: source.id.startsWith("screen:") ? "screen" : "window",
    thumbnailUrl: nativeImageToDataUrl(source.thumbnail),
    appIconUrl: nativeImageToDataUrl(source.appIcon)
  })).sort((left, right) => {
    if (left.kind !== right.kind) {
      return left.kind === "screen" ? -1 : 1;
    }
    return left.source.name.localeCompare(right.source.name);
  });
  return new Promise((resolve, reject) => {
    const modal = new DesktopSourceModal(
      app,
      options,
      resolve,
      reject
    );
    modal.open();
  });
}
var DesktopSourceModal = class extends import_obsidian.SuggestModal {
  constructor(app, sources, resolveSelection, rejectSelection) {
    super(app);
    this.sources = sources;
    this.resolveSelection = resolveSelection;
    this.rejectSelection = rejectSelection;
    this.settled = false;
    this.limit = Math.max(20, sources.length);
    this.emptyStateText = "\u6CA1\u6709\u5339\u914D\u7684\u5C4F\u5E55\u6216\u7A97\u53E3";
    this.setPlaceholder("\u641C\u7D22\u5C4F\u5E55\u6216\u7A97\u53E3");
    this.setInstructions([
      { command: "\u2191\u2193", purpose: "\u9009\u62E9" },
      { command: "\u21B5", purpose: "\u5F55\u5236" },
      { command: "esc", purpose: "\u53D6\u6D88" }
    ]);
    this.modalEl.addClass("screen-recorder-source-modal");
  }
  getSuggestions(query) {
    const normalizedQuery = query.trim().toLocaleLowerCase();
    if (!normalizedQuery) {
      return this.sources;
    }
    return this.sources.filter(
      (option) => option.source.name.toLocaleLowerCase().includes(normalizedQuery)
    );
  }
  renderSuggestion(option, el) {
    el.addClass("screen-recorder-source-suggestion");
    const previewEl = el.createDiv({
      cls: "screen-recorder-source-preview"
    });
    if (option.thumbnailUrl) {
      const imageEl = previewEl.createEl("img");
      imageEl.src = option.thumbnailUrl;
      imageEl.alt = "";
    } else {
      (0, import_obsidian.setIcon)(
        previewEl,
        option.kind === "screen" ? "monitor" : "app-window"
      );
    }
    const detailsEl = el.createDiv({
      cls: "screen-recorder-source-details"
    });
    const titleRowEl = detailsEl.createDiv({
      cls: "screen-recorder-source-title-row"
    });
    if (option.appIconUrl) {
      const appIconEl = titleRowEl.createEl("img", {
        cls: "screen-recorder-source-app-icon"
      });
      appIconEl.src = option.appIconUrl;
      appIconEl.alt = "";
    }
    titleRowEl.createDiv({
      cls: "screen-recorder-source-name",
      text: option.source.name
    });
    detailsEl.createDiv({
      cls: "screen-recorder-source-kind",
      text: option.kind === "screen" ? "\u663E\u793A\u5668" : "\u5E94\u7528\u7A97\u53E3"
    });
  }
  onChooseSuggestion(option) {
    if (this.settled) {
      return;
    }
    this.settled = true;
    this.resolveSelection(option);
  }
  onClose() {
    super.onClose();
    if (this.settled) {
      return;
    }
    this.settled = true;
    this.rejectSelection(
      new DOMException("\u5C4F\u5E55\u9009\u62E9\u5DF2\u53D6\u6D88", "AbortError")
    );
  }
};
function nativeImageToDataUrl(image) {
  var _a;
  try {
    if (!(image == null ? void 0 : image.toDataURL) || ((_a = image.isEmpty) == null ? void 0 : _a.call(image))) {
      return "";
    }
    return image.toDataURL();
  } catch (e) {
    return "";
  }
}
function describeError(error) {
  if (error instanceof Error) {
    return [error.name, error.message].filter(Boolean).join(": ");
  }
  if (typeof error === "string" && error) {
    return error;
  }
  if (error && typeof error === "object") {
    const details = error;
    const description = [details.name, details.code, details.message].filter(
      (value) => typeof value === "string" || typeof value === "number"
    ).map(String).filter(Boolean).join(": ");
    if (description) {
      return description;
    }
  }
  return "\u672A\u77E5\u9519\u8BEF";
}

// src/native-camera.ts
var import_crypto = require("crypto");
var import_fs = require("fs");
var import_net = require("net");
var import_child_process = require("child_process");
var BRIDGE_CONNECT_TIMEOUT_MS = 1e4;
var BRIDGE_FIRST_FRAME_TIMEOUT_MS = 6e4;
var BRIDGE_MAX_MESSAGE_SIZE = 8 * 1024 * 1024;
var MESSAGE_HEADER_SIZE = 5;
var NativeCameraBridge = class _NativeCameraBridge {
  constructor(socket, frameRate) {
    this.receiveBuffer = Buffer.alloc(0);
    this.queuedFrame = null;
    this.decodingFrame = false;
    this.firstFrameSettled = false;
    this.disposed = false;
    this.socket = socket;
    this.canvas = document.createElement("canvas");
    this.canvas.width = 1280;
    this.canvas.height = 720;
    const ctx = this.canvas.getContext("2d", {
      alpha: false,
      desynchronized: true
    });
    if (!ctx) {
      throw new Error("\u65E0\u6CD5\u521D\u59CB\u5316\u539F\u751F\u6444\u50CF\u5934\u753B\u5E03");
    }
    this.ctx = ctx;
    this.ctx.fillStyle = "#111111";
    this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
    this.stream = this.canvas.captureStream(frameRate);
    this.firstFramePromise = new Promise((resolve, reject) => {
      this.resolveFirstFrame = resolve;
      this.rejectFirstFrame = reject;
    });
    this.socket.on("data", (chunk) => {
      this.handleData(
        typeof chunk === "string" ? Buffer.from(chunk) : chunk
      );
    });
    this.socket.on("error", (error) => {
      this.rejectBeforeFirstFrame(
        new Error(`\u539F\u751F\u6444\u50CF\u5934\u8FDE\u63A5\u5931\u8D25\uFF1A${error.message}`)
      );
    });
    this.socket.on("close", () => {
      this.rejectBeforeFirstFrame(
        new Error("\u539F\u751F\u6444\u50CF\u5934\u8FDE\u63A5\u5DF2\u5173\u95ED")
      );
    });
  }
  static async open(appPath, frameRate) {
    if (process.platform !== "darwin") {
      throw new Error("\u539F\u751F\u6444\u50CF\u5934\u6865\u63A5\u4EC5\u652F\u6301 macOS");
    }
    if (!(0, import_fs.existsSync)(appPath)) {
      throw new Error(`\u672A\u627E\u5230\u539F\u751F\u6444\u50CF\u5934\u6865\u63A5\u7A0B\u5E8F\uFF1A${appPath}`);
    }
    const port = await findAvailablePort();
    const token = (0, import_crypto.randomBytes)(24).toString("hex");
    const launcher = (0, import_child_process.spawn)(
      "/usr/bin/open",
      [
        "-n",
        appPath,
        "--args",
        "--port",
        String(port),
        "--token",
        token
      ],
      {
        detached: true,
        stdio: "ignore"
      }
    );
    launcher.unref();
    const socket = await connectWithRetry(port);
    const bridge = new _NativeCameraBridge(socket, frameRate);
    socket.write(`${token}
`);
    try {
      await bridge.waitForFirstFrame();
      return bridge;
    } catch (error) {
      bridge.dispose();
      throw error;
    }
  }
  getStream() {
    return this.stream;
  }
  dispose() {
    if (this.disposed) {
      return;
    }
    this.disposed = true;
    this.socket.destroy();
    for (const track of this.stream.getTracks()) {
      track.stop();
    }
    this.canvas.remove();
  }
  waitForFirstFrame() {
    return new Promise((resolve, reject) => {
      const timeoutId = window.setTimeout(() => {
        reject(
          new Error(
            "\u539F\u751F\u6444\u50CF\u5934\u7B49\u5F85\u753B\u9762\u8D85\u65F6\u3002\u82E5\u51FA\u73B0\u6743\u9650\u5F39\u7A97\uFF0C\u8BF7\u5141\u8BB8 Obsidian Camera Bridge \u4F7F\u7528\u6444\u50CF\u5934"
          )
        );
      }, BRIDGE_FIRST_FRAME_TIMEOUT_MS);
      void this.firstFramePromise.then(
        () => {
          window.clearTimeout(timeoutId);
          resolve();
        },
        (error) => {
          window.clearTimeout(timeoutId);
          reject(error);
        }
      );
    });
  }
  handleData(chunk) {
    if (this.disposed) {
      return;
    }
    this.receiveBuffer = Buffer.concat([this.receiveBuffer, chunk]);
    while (this.receiveBuffer.length >= MESSAGE_HEADER_SIZE) {
      const type = this.receiveBuffer[0];
      const length = this.receiveBuffer.readUInt32BE(1);
      if (length > BRIDGE_MAX_MESSAGE_SIZE) {
        this.rejectBeforeFirstFrame(
          new Error("\u539F\u751F\u6444\u50CF\u5934\u8FD4\u56DE\u4E86\u65E0\u6548\u6570\u636E")
        );
        this.dispose();
        return;
      }
      if (this.receiveBuffer.length < MESSAGE_HEADER_SIZE + length) {
        return;
      }
      const payload = Buffer.from(
        this.receiveBuffer.subarray(
          MESSAGE_HEADER_SIZE,
          MESSAGE_HEADER_SIZE + length
        )
      );
      this.receiveBuffer = this.receiveBuffer.subarray(
        MESSAGE_HEADER_SIZE + length
      );
      this.handleMessage(type, payload);
    }
  }
  handleMessage(type, payload) {
    if (type === 1 /* Frame */) {
      this.queuedFrame = payload;
      if (!this.decodingFrame) {
        void this.decodeQueuedFrames();
      }
      return;
    }
    if (type === 2 /* Error */) {
      const message = payload.toString("utf8").trim() || "\u539F\u751F\u6444\u50CF\u5934\u521D\u59CB\u5316\u5931\u8D25";
      this.rejectBeforeFirstFrame(
        new Error(this.translateBridgeError(message))
      );
      this.dispose();
    }
  }
  async decodeQueuedFrames() {
    this.decodingFrame = true;
    try {
      while (this.queuedFrame && !this.disposed) {
        const payload = this.queuedFrame;
        this.queuedFrame = null;
        const jpeg = Uint8Array.from(payload);
        const bitmap = await createImageBitmap(
          new Blob([jpeg.buffer], { type: "image/jpeg" })
        );
        try {
          this.ctx.drawImage(
            bitmap,
            0,
            0,
            this.canvas.width,
            this.canvas.height
          );
          if (!this.firstFrameSettled) {
            this.firstFrameSettled = true;
            this.resolveFirstFrame();
          }
        } finally {
          bitmap.close();
        }
      }
    } catch (error) {
      this.rejectBeforeFirstFrame(
        new Error(
          `\u539F\u751F\u6444\u50CF\u5934\u753B\u9762\u89E3\u7801\u5931\u8D25\uFF1A${describeUnknownError(error)}`
        )
      );
    } finally {
      this.decodingFrame = false;
      if (this.queuedFrame && !this.disposed) {
        void this.decodeQueuedFrames();
      }
    }
  }
  rejectBeforeFirstFrame(error) {
    if (this.firstFrameSettled) {
      return;
    }
    this.firstFrameSettled = true;
    this.rejectFirstFrame(error);
  }
  translateBridgeError(message) {
    if (/permission was denied/i.test(message)) {
      return "\u6444\u50CF\u5934\u6743\u9650\u5DF2\u62D2\u7EDD\u3002\u8BF7\u6253\u5F00\u201C\u7CFB\u7EDF\u8BBE\u7F6E \u2192 \u9690\u79C1\u4E0E\u5B89\u5168\u6027 \u2192 \u6444\u50CF\u5934\u201D\uFF0C\u5141\u8BB8 Obsidian Camera Bridge\uFF0C\u7136\u540E\u91CD\u8BD5";
    }
    if (/restricted/i.test(message)) {
      return "\u6444\u50CF\u5934\u8BBF\u95EE\u53D7\u5230 macOS \u9650\u5236";
    }
    if (/no camera/i.test(message)) {
      return "\u539F\u751F\u6444\u50CF\u5934\u6865\u63A5\u7A0B\u5E8F\u6CA1\u6709\u627E\u5230\u6444\u50CF\u5934";
    }
    return `\u539F\u751F\u6444\u50CF\u5934\u521D\u59CB\u5316\u5931\u8D25\uFF1A${message}`;
  }
};
function findAvailablePort() {
  return new Promise((resolve, reject) => {
    const server = (0, import_net.createServer)();
    server.unref();
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      if (!address || typeof address === "string") {
        server.close();
        reject(new Error("\u65E0\u6CD5\u5206\u914D\u539F\u751F\u6444\u50CF\u5934\u7AEF\u53E3"));
        return;
      }
      const port = address.port;
      server.close((error) => {
        if (error) {
          reject(error);
          return;
        }
        resolve(port);
      });
    });
  });
}
async function connectWithRetry(port) {
  const startedAt = Date.now();
  let lastError = null;
  while (Date.now() - startedAt < BRIDGE_CONNECT_TIMEOUT_MS) {
    try {
      return await connectOnce(port);
    } catch (error) {
      lastError = error instanceof Error ? error : new Error(String(error));
      await delay(150);
    }
  }
  throw new Error(
    `\u65E0\u6CD5\u542F\u52A8\u539F\u751F\u6444\u50CF\u5934\u6865\u63A5\u7A0B\u5E8F${(lastError == null ? void 0 : lastError.message) ? `\uFF1A${lastError.message}` : ""}`
  );
}
function connectOnce(port) {
  return new Promise((resolve, reject) => {
    const socket = (0, import_net.createConnection)({
      host: "127.0.0.1",
      port
    });
    const handleError = (error) => {
      socket.destroy();
      reject(error);
    };
    socket.once("error", handleError);
    socket.once("connect", () => {
      socket.removeListener("error", handleError);
      resolve(socket);
    });
  });
}
function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
function describeUnknownError(error) {
  if (error instanceof Error) {
    return error.message || error.name;
  }
  return String(error);
}

// src/types.ts
var DEFAULT_SETTINGS = {
  videoFormat: "mp4",
  videoQuality: "high",
  cameraSize: "medium",
  cameraPosition: "bottom-right",
  cameraShape: "circle",
  frameRate: 30,
  enableCamera: true,
  enableMicrophone: true,
  enableSystemAudio: true,
  showCursor: true,
  countdownSeconds: 3,
  recordingsFolder: "recordings",
  insertRecordingLink: true
};
var VIDEO_BITRATES = {
  high: 8e6,
  medium: 5e6,
  low: 25e5
};
var MAX_OUTPUT_WIDTHS = {
  high: 2560,
  medium: 1920,
  low: 1280
};
var CAMERA_PREVIEW_SIZES = {
  small: 132,
  medium: 168,
  large: 216
};
var CAMERA_OUTPUT_RATIOS = {
  small: 0.14,
  medium: 0.18,
  large: 0.24
};
var CAMERA_POSITION_COORDINATES = {
  "top-left": { x: 0, y: 0 },
  "top-right": { x: 1, y: 0 },
  "bottom-left": { x: 0, y: 1 },
  "bottom-right": { x: 1, y: 1 }
};

// src/recorder.ts
var CAMERA_PROBE_TIMEOUT_MS = 6e3;
var MAX_CAMERA_DEVICE_ATTEMPTS = 6;
var ScreenCameraRecorder = class {
  constructor(app, settings, callbacks, nativeCameraAppPath) {
    this.screenStream = null;
    this.cameraStream = null;
    this.microphoneStream = null;
    this.nativeCameraBridge = null;
    this.composedStream = null;
    this.audioContext = null;
    this.audioSources = [];
    this.audioDestination = null;
    this.mediaRecorder = null;
    this.recordedChunks = [];
    this.animationFrameId = null;
    this.mimeType = "";
    this.status = "idle" /* Idle */;
    this.startedAt = 0;
    this.pausedAt = 0;
    this.totalPausedMs = 0;
    this.disposed = false;
    this.app = app;
    this.settings = settings;
    this.callbacks = callbacks;
    this.nativeCameraAppPath = nativeCameraAppPath;
    this.cameraPosition = {
      ...CAMERA_POSITION_COORDINATES[settings.cameraPosition]
    };
    this.cameraVisible = settings.enableCamera;
    this.canvas = document.createElement("canvas");
    const ctx = this.canvas.getContext("2d", {
      alpha: false,
      desynchronized: true
    });
    if (!ctx) {
      throw new Error("\u65E0\u6CD5\u521D\u59CB\u5316\u89C6\u9891\u5408\u6210\u753B\u5E03");
    }
    this.ctx = ctx;
    this.mediaHost = document.createElement("div");
    this.mediaHost.setAttribute("aria-hidden", "true");
    Object.assign(this.mediaHost.style, {
      position: "fixed",
      left: "0",
      bottom: "0",
      width: "2px",
      height: "2px",
      overflow: "hidden",
      opacity: "0.001",
      pointerEvents: "none",
      zIndex: "2147483647"
    });
    document.body.appendChild(this.mediaHost);
    this.screenVideo = this.createVideoElement();
    this.cameraVideo = this.createVideoElement();
  }
  async prepare() {
    var _a;
    if (this.status !== "idle" /* Idle */) {
      throw new Error("\u5F55\u5236\u5668\u6B63\u5728\u8FD0\u884C");
    }
    this.status = "starting" /* Starting */;
    const warnings = [];
    try {
      this.screenStream = await this.getDisplayStream(warnings);
      this.assertActive();
      const displayTrack = this.screenStream.getVideoTracks()[0];
      if (!displayTrack) {
        throw new Error("\u6CA1\u6709\u83B7\u53D6\u5230\u53EF\u5F55\u5236\u7684\u5C4F\u5E55\u753B\u9762");
      }
      displayTrack.addEventListener(
        "ended",
        () => {
          if (this.status === "starting" /* Starting */ || this.status === "recording" /* Recording */ || this.status === "paused" /* Paused */) {
            this.callbacks.onDisplayEnded();
          }
        },
        { once: true }
      );
      if (this.settings.enableCamera) {
        await this.initializeCamera();
        this.assertActive();
      }
      if (this.settings.enableMicrophone) {
        try {
          this.microphoneStream = await navigator.mediaDevices.getUserMedia({
            video: false,
            audio: {
              echoCancellation: true,
              noiseSuppression: true,
              autoGainControl: true,
              channelCount: { ideal: 1 }
            }
          });
          this.assertActive();
        } catch (error) {
          this.assertActive();
          warnings.push(this.describeMediaError(error, "\u9EA6\u514B\u98CE\u4E0D\u53EF\u7528"));
        }
      }
      this.screenVideo.srcObject = this.screenStream;
      await this.waitForVideoReady(this.screenVideo, "\u5C4F\u5E55\u753B\u9762");
      this.assertActive();
      this.configureCanvas();
      this.composedStream = this.canvas.captureStream(
        this.settings.frameRate
      );
      await this.attachAudioTracks(this.composedStream, warnings);
      this.mimeType = this.getSupportedMimeType();
      if (!this.mimeType) {
        throw new Error("\u5F53\u524D Obsidian \u7248\u672C\u4E0D\u652F\u6301\u89C6\u9891\u5F55\u5236");
      }
      this.mediaRecorder = new MediaRecorder(this.composedStream, {
        mimeType: this.mimeType,
        videoBitsPerSecond: VIDEO_BITRATES[this.settings.videoQuality],
        audioBitsPerSecond: 192e3
      });
      this.mimeType = this.mediaRecorder.mimeType || this.mimeType;
      const actualFormat = this.mimeType.startsWith("video/mp4") ? "mp4" : "webm";
      if (actualFormat !== this.settings.videoFormat) {
        warnings.push(
          `\u5F53\u524D Obsidian \u4E0D\u652F\u6301\u76F4\u63A5\u5F55\u5236 ${this.settings.videoFormat.toUpperCase()}\uFF0C\u672C\u6B21\u5C06\u4FDD\u5B58\u4E3A ${actualFormat.toUpperCase()}`
        );
      }
      return {
        cameraAvailable: Boolean(this.cameraStream),
        microphoneAvailable: Boolean(
          (_a = this.microphoneStream) == null ? void 0 : _a.getAudioTracks().length
        ),
        systemAudioAvailable: this.screenStream.getAudioTracks().length > 0,
        warnings
      };
    } catch (error) {
      this.status = "error" /* Error */;
      await this.cleanup();
      throw error;
    }
  }
  beginRecording() {
    if (this.status !== "starting" /* Starting */ || !this.mediaRecorder || this.disposed) {
      throw new Error("\u5F55\u5236\u5668\u5C1A\u672A\u51C6\u5907\u5B8C\u6210");
    }
    this.recordedChunks = [];
    this.mediaRecorder.ondataavailable = (event) => {
      if (event.data.size > 0) {
        this.recordedChunks.push(event.data);
      }
    };
    this.startDrawing();
    this.mediaRecorder.start(1e3);
    this.startedAt = performance.now();
    this.pausedAt = 0;
    this.totalPausedMs = 0;
    this.status = "recording" /* Recording */;
  }
  pause() {
    if (this.status !== "recording" /* Recording */ || !this.mediaRecorder || this.mediaRecorder.state !== "recording") {
      return;
    }
    this.mediaRecorder.pause();
    this.pausedAt = performance.now();
    this.status = "paused" /* Paused */;
  }
  resume() {
    if (this.status !== "paused" /* Paused */ || !this.mediaRecorder || this.mediaRecorder.state !== "paused") {
      return;
    }
    this.mediaRecorder.resume();
    if (this.pausedAt > 0) {
      this.totalPausedMs += performance.now() - this.pausedAt;
    }
    this.pausedAt = 0;
    this.status = "recording" /* Recording */;
  }
  async stopRecording() {
    if (this.status !== "recording" /* Recording */ && this.status !== "paused" /* Paused */) {
      throw new Error("\u5F53\u524D\u6CA1\u6709\u6B63\u5728\u8FDB\u884C\u7684\u5F55\u5236");
    }
    this.status = "stopping" /* Stopping */;
    this.stopDrawing();
    try {
      const blob = await this.finalizeRecorder();
      if (blob.size === 0) {
        throw new Error("\u5F55\u5236\u7ED3\u679C\u4E3A\u7A7A\uFF0C\u8BF7\u91CD\u65B0\u5C1D\u8BD5");
      }
      return blob;
    } finally {
      await this.cleanup();
      this.status = "idle" /* Idle */;
    }
  }
  async cancelRecording() {
    this.disposed = true;
    this.stopDrawing();
    const recorder = this.mediaRecorder;
    if (recorder && recorder.state !== "inactive") {
      recorder.ondataavailable = null;
      recorder.onstop = null;
      recorder.onerror = null;
      recorder.stop();
    }
    this.recordedChunks = [];
    await this.cleanup();
    this.status = "idle" /* Idle */;
  }
  dispose() {
    this.disposed = true;
    this.stopDrawing();
    const recorder = this.mediaRecorder;
    if (recorder && recorder.state !== "inactive") {
      recorder.ondataavailable = null;
      recorder.onstop = null;
      recorder.onerror = null;
      recorder.stop();
    }
    void this.cleanup();
    this.status = "idle" /* Idle */;
  }
  getStatus() {
    return this.status;
  }
  getCameraStream() {
    return this.cameraStream;
  }
  getElapsedMs() {
    if (!this.startedAt) {
      return 0;
    }
    const end = this.status === "paused" /* Paused */ && this.pausedAt ? this.pausedAt : performance.now();
    return Math.max(0, end - this.startedAt - this.totalPausedMs);
  }
  setCameraPosition(position) {
    this.cameraPosition = {
      x: this.clamp(position.x, 0, 1),
      y: this.clamp(position.y, 0, 1)
    };
  }
  setCameraVisible(visible) {
    this.cameraVisible = visible && Boolean(this.cameraStream);
  }
  createVideoElement() {
    const video = document.createElement("video");
    video.autoplay = true;
    video.defaultMuted = true;
    video.muted = true;
    video.playsInline = true;
    video.setAttribute("autoplay", "");
    video.setAttribute("muted", "");
    video.setAttribute("playsinline", "");
    video.style.position = "absolute";
    video.style.inset = "0";
    video.style.width = "2px";
    video.style.height = "2px";
    this.mediaHost.appendChild(video);
    return video;
  }
  async initializeCamera() {
    var _a, _b, _c;
    const failures = [];
    let defaultDeviceId = "";
    let defaultTrackOpened = false;
    if (process.platform === "darwin") {
      try {
        const bridge = await NativeCameraBridge.open(
          this.nativeCameraAppPath,
          this.settings.frameRate
        );
        this.nativeCameraBridge = bridge;
        this.assertActive();
        if (await this.tryCameraStream(
          bridge.getStream(),
          "Obsidian Camera Bridge",
          failures
        )) {
          return;
        }
        throw new Error(
          (_a = failures[failures.length - 1]) != null ? _a : "\u539F\u751F\u6444\u50CF\u5934\u6865\u63A5\u6CA1\u6709\u8F93\u51FA\u753B\u9762"
        );
      } catch (error) {
        (_b = this.nativeCameraBridge) == null ? void 0 : _b.dispose();
        this.nativeCameraBridge = null;
        this.assertActive();
        throw new Error(
          `Obsidian Camera Bridge\uFF1A${this.describeUnknownError(
            error
          )}`
        );
      }
    }
    try {
      const defaultStream = await navigator.mediaDevices.getUserMedia({
        video: this.getCameraConstraints(),
        audio: false
      });
      this.assertActive();
      const defaultTrack = defaultStream.getVideoTracks()[0];
      defaultTrackOpened = Boolean(defaultTrack);
      defaultDeviceId = (_c = defaultTrack == null ? void 0 : defaultTrack.getSettings().deviceId) != null ? _c : "";
      const defaultLabel = (defaultTrack == null ? void 0 : defaultTrack.label.trim()) || "\u9ED8\u8BA4\u6444\u50CF\u5934";
      if (await this.tryCameraStream(
        defaultStream,
        defaultLabel,
        failures
      )) {
        return;
      }
    } catch (error) {
      this.assertActive();
      if (this.isCameraPermissionError(error)) {
        throw new Error(
          this.describeMediaError(error, "\u6444\u50CF\u5934\u4E0D\u53EF\u7528")
        );
      }
      failures.push(
        `\u9ED8\u8BA4\u6444\u50CF\u5934\uFF1A${this.describeMediaError(
          error,
          "\u6253\u5F00\u5931\u8D25"
        )}`
      );
    }
    const cameras = await this.enumerateCameras(failures);
    const candidates = cameras.filter((device) => device.deviceId !== defaultDeviceId).slice(0, MAX_CAMERA_DEVICE_ATTEMPTS);
    for (const [index, device] of candidates.entries()) {
      this.assertActive();
      const label = device.label.trim() || `\u6444\u50CF\u5934 ${index + 1}`;
      let stream;
      try {
        stream = await navigator.mediaDevices.getUserMedia({
          video: this.getCameraConstraints(device.deviceId),
          audio: false
        });
        this.assertActive();
      } catch (error) {
        this.assertActive();
        if (this.isCameraPermissionError(error)) {
          throw new Error(
            this.describeMediaError(error, "\u6444\u50CF\u5934\u4E0D\u53EF\u7528")
          );
        }
        failures.push(
          `${label}\uFF1A${this.describeMediaError(
            error,
            "\u6253\u5F00\u5931\u8D25"
          )}`
        );
        continue;
      }
      if (await this.tryCameraStream(stream, label, failures)) {
        return;
      }
    }
    const detectedCount = Math.max(
      cameras.length,
      defaultTrackOpened ? 1 : 0
    );
    const summary = detectedCount > 0 ? `\u68C0\u6D4B\u5230 ${detectedCount} \u4E2A\u6444\u50CF\u5934\uFF0C\u4F46\u90FD\u6CA1\u6709\u8F93\u51FA\u753B\u9762` : "\u7CFB\u7EDF\u6CA1\u6709\u5411 Obsidian \u63D0\u4F9B\u53EF\u7528\u6444\u50CF\u5934";
    const details = failures.length > 0 ? `\u3002\u5C1D\u8BD5\u7ED3\u679C\uFF1A${failures.join("\uFF1B")}` : "";
    throw new Error(
      `\u6444\u50CF\u5934\u521D\u59CB\u5316\u5931\u8D25\uFF1A${summary}\u3002\u8BF7\u786E\u8BA4\u6444\u50CF\u5934\u5DF2\u8FDE\u63A5\u3001\u672A\u88AB\u5176\u4ED6\u5E94\u7528\u5360\u7528\uFF0C\u5E76\u5728\u7CFB\u7EDF\u9690\u79C1\u8BBE\u7F6E\u4E2D\u5141\u8BB8 Obsidian \u4F7F\u7528\u6444\u50CF\u5934${details}`
    );
  }
  getCameraConstraints(deviceId) {
    return {
      width: { ideal: 1280 },
      height: { ideal: 720 },
      frameRate: { ideal: this.settings.frameRate },
      ...deviceId ? { deviceId: { exact: deviceId } } : {}
    };
  }
  async enumerateCameras(failures) {
    try {
      const devices = await navigator.mediaDevices.enumerateDevices();
      const seen = /* @__PURE__ */ new Set();
      return devices.filter((device) => {
        if (device.kind !== "videoinput" || !device.deviceId || seen.has(device.deviceId)) {
          return false;
        }
        seen.add(device.deviceId);
        return true;
      });
    } catch (error) {
      failures.push(
        `\u8BFB\u53D6\u6444\u50CF\u5934\u5217\u8868\u5931\u8D25\uFF1A${this.describeUnknownError(error)}`
      );
      return [];
    }
  }
  async tryCameraStream(stream, label, failures) {
    const track = stream.getVideoTracks()[0];
    if (!track) {
      failures.push(`${label}\uFF1A\u6CA1\u6709\u8FD4\u56DE\u89C6\u9891\u8F68\u9053`);
      this.stopStream(stream);
      return false;
    }
    this.cameraStream = stream;
    this.cameraVideo.srcObject = stream;
    try {
      await this.waitForVideoReady(
        this.cameraVideo,
        "\u6444\u50CF\u5934",
        CAMERA_PROBE_TIMEOUT_MS
      );
      this.assertActive();
      return true;
    } catch (error) {
      this.assertActive();
      const message = error instanceof Error ? error.message || error.name : String(error);
      failures.push(`${label}\uFF1A${message}`);
      this.releaseCameraStream(stream);
      return false;
    }
  }
  releaseCameraStream(stream) {
    var _a;
    if (this.cameraVideo.srcObject === stream) {
      this.cameraVideo.pause();
      this.cameraVideo.srcObject = null;
    }
    this.stopStream(stream);
    if (this.cameraStream === stream) {
      this.cameraStream = null;
    }
    if (((_a = this.nativeCameraBridge) == null ? void 0 : _a.getStream()) === stream) {
      this.nativeCameraBridge.dispose();
      this.nativeCameraBridge = null;
    }
  }
  isCameraPermissionError(error) {
    return error instanceof DOMException && (error.name === "NotAllowedError" || error.name === "SecurityError");
  }
  async getDisplayStream(warnings) {
    try {
      return await navigator.mediaDevices.getDisplayMedia({
        video: {
          frameRate: {
            ideal: this.settings.frameRate,
            max: this.settings.frameRate
          },
          cursor: this.settings.showCursor ? "always" : "never"
        },
        audio: this.settings.enableSystemAudio
      });
    } catch (error) {
      if (!this.isDisplayMediaUnsupported(error)) {
        throw error;
      }
    }
    return captureDesktopWithElectron(
      this.app,
      {
        frameRate: this.settings.frameRate,
        showCursor: this.settings.showCursor,
        enableSystemAudio: this.settings.enableSystemAudio
      },
      warnings
    );
  }
  isDisplayMediaUnsupported(error) {
    if (error instanceof DOMException) {
      return error.name === "NotSupportedError" || /not supported/i.test(error.message);
    }
    return error instanceof Error && /not supported/i.test(error.message);
  }
  configureCanvas() {
    const sourceWidth = this.screenVideo.videoWidth;
    const sourceHeight = this.screenVideo.videoHeight;
    const maxWidth = MAX_OUTPUT_WIDTHS[this.settings.videoQuality];
    const scale = Math.min(1, maxWidth / sourceWidth);
    this.canvas.width = this.makeEven(Math.round(sourceWidth * scale));
    this.canvas.height = this.makeEven(Math.round(sourceHeight * scale));
  }
  async attachAudioTracks(targetStream, warnings) {
    var _a, _b, _c, _d;
    const tracks = [
      ...(_b = (_a = this.screenStream) == null ? void 0 : _a.getAudioTracks()) != null ? _b : [],
      ...(_d = (_c = this.microphoneStream) == null ? void 0 : _c.getAudioTracks()) != null ? _d : []
    ].filter((track) => track.readyState === "live");
    if (tracks.length === 0) {
      if (this.settings.enableSystemAudio) {
        warnings.push(
          "\u6240\u9009\u5171\u4EAB\u6E90\u6CA1\u6709\u7CFB\u7EDF\u97F3\u9891\uFF1B\u9700\u8981\u65F6\u8BF7\u5728\u5171\u4EAB\u7A97\u53E3\u4E2D\u542F\u7528\u97F3\u9891"
        );
      }
      return;
    }
    try {
      this.audioContext = new AudioContext();
      this.audioDestination = this.audioContext.createMediaStreamDestination();
      for (const track of tracks) {
        const source = this.audioContext.createMediaStreamSource(
          new MediaStream([track])
        );
        source.connect(this.audioDestination);
        this.audioSources.push(source);
      }
      if (this.audioContext.state === "suspended") {
        await this.audioContext.resume();
      }
      for (const track of this.audioDestination.stream.getAudioTracks()) {
        targetStream.addTrack(track);
      }
    } catch (error) {
      warnings.push(
        this.describeMediaError(error, "\u97F3\u9891\u6DF7\u97F3\u5931\u8D25\uFF0C\u5C06\u4EC5\u5F55\u5236\u4E00\u4E2A\u97F3\u6E90")
      );
      targetStream.addTrack(tracks[0].clone());
    }
  }
  startDrawing() {
    const draw = () => {
      this.drawComposition();
      this.animationFrameId = requestAnimationFrame(draw);
    };
    draw();
  }
  stopDrawing() {
    if (this.animationFrameId !== null) {
      cancelAnimationFrame(this.animationFrameId);
      this.animationFrameId = null;
    }
  }
  drawComposition() {
    this.ctx.fillStyle = "#111111";
    this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
    this.ctx.drawImage(
      this.screenVideo,
      0,
      0,
      this.canvas.width,
      this.canvas.height
    );
    if (this.cameraVisible && this.cameraStream && this.cameraVideo.readyState >= HTMLMediaElement.HAVE_CURRENT_DATA) {
      this.drawCameraBubble();
    }
  }
  drawCameraBubble() {
    const shortestSide = Math.min(this.canvas.width, this.canvas.height);
    const size = Math.round(
      this.clamp(
        shortestSide * CAMERA_OUTPUT_RATIOS[this.settings.cameraSize],
        120,
        480
      )
    );
    const margin = Math.max(20, Math.round(shortestSide * 0.025));
    const availableWidth = Math.max(
      0,
      this.canvas.width - size - margin * 2
    );
    const availableHeight = Math.max(
      0,
      this.canvas.height - size - margin * 2
    );
    const x = margin + availableWidth * this.cameraPosition.x;
    const y = margin + availableHeight * this.cameraPosition.y;
    const borderWidth = Math.max(3, Math.round(size * 0.018));
    this.ctx.save();
    this.ctx.shadowColor = "rgba(0, 0, 0, 0.32)";
    this.ctx.shadowBlur = Math.round(size * 0.08);
    this.ctx.shadowOffsetY = Math.round(size * 0.025);
    this.createCameraPath(x, y, size);
    this.ctx.fillStyle = "#ffffff";
    this.ctx.fill();
    this.ctx.restore();
    this.ctx.save();
    this.createCameraPath(
      x + borderWidth,
      y + borderWidth,
      size - borderWidth * 2
    );
    this.ctx.clip();
    this.drawMirroredCameraFrame(
      x + borderWidth,
      y + borderWidth,
      size - borderWidth * 2
    );
    this.ctx.restore();
  }
  createCameraPath(x, y, size) {
    this.ctx.beginPath();
    if (this.settings.cameraShape === "circle") {
      this.ctx.arc(
        x + size / 2,
        y + size / 2,
        size / 2,
        0,
        Math.PI * 2
      );
    } else {
      const radius = Math.round(size * 0.2);
      this.ctx.roundRect(x, y, size, size, radius);
    }
    this.ctx.closePath();
  }
  drawMirroredCameraFrame(x, y, size) {
    const sourceWidth = this.cameraVideo.videoWidth;
    const sourceHeight = this.cameraVideo.videoHeight;
    const cropSize = Math.min(sourceWidth, sourceHeight);
    const sourceX = (sourceWidth - cropSize) / 2;
    const sourceY = (sourceHeight - cropSize) / 2;
    this.ctx.translate(x + size, y);
    this.ctx.scale(-1, 1);
    this.ctx.drawImage(
      this.cameraVideo,
      sourceX,
      sourceY,
      cropSize,
      cropSize,
      0,
      0,
      size,
      size
    );
  }
  finalizeRecorder() {
    const recorder = this.mediaRecorder;
    if (!recorder) {
      return Promise.reject(new Error("\u5F55\u5236\u5668\u672A\u521D\u59CB\u5316"));
    }
    if (recorder.state === "inactive") {
      return Promise.resolve(
        new Blob(this.recordedChunks, { type: this.mimeType })
      );
    }
    return new Promise((resolve, reject) => {
      let settled = false;
      let timeoutId = null;
      const finish = (callback) => {
        if (settled) return;
        settled = true;
        if (timeoutId !== null) {
          window.clearTimeout(timeoutId);
        }
        callback();
      };
      timeoutId = window.setTimeout(() => {
        finish(() => reject(new Error("\u89C6\u9891\u7F16\u7801\u7ED3\u675F\u8D85\u65F6")));
      }, 3e4);
      recorder.onstop = () => {
        finish(() => {
          resolve(
            new Blob(this.recordedChunks, {
              type: this.mimeType
            })
          );
        });
      };
      recorder.onerror = (event) => {
        const errorEvent = event;
        finish(() => {
          var _a;
          reject(
            (_a = errorEvent.error) != null ? _a : new Error("\u89C6\u9891\u7F16\u7801\u8FC7\u7A0B\u4E2D\u53D1\u751F\u9519\u8BEF")
          );
        });
      };
      try {
        recorder.requestData();
        recorder.stop();
      } catch (error) {
        finish(() => reject(error));
      }
    });
  }
  waitForVideoReady(video, label, timeoutMs = 15e3) {
    return new Promise((resolve, reject) => {
      let settled = false;
      let frameCallbackId = null;
      let frameFallbackId = null;
      let playbackError = null;
      const track = video.srcObject instanceof MediaStream ? video.srcObject.getVideoTracks()[0] : null;
      const timeoutId = window.setTimeout(() => {
        const details = [
          track ? `\u8F68\u9053 ${track.readyState}` : "",
          (track == null ? void 0 : track.muted) ? "\u8F68\u9053\u65E0\u753B\u9762" : "",
          playbackError ? `\u64AD\u653E\u5931\u8D25\uFF1A${this.describeUnknownError(
            playbackError
          )}` : ""
        ].filter(Boolean).join("\uFF0C");
        finish(
          () => reject(
            new Error(
              `${label}\u521D\u59CB\u5316\u8D85\u65F6${details ? `\uFF08${details}\uFF09` : ""}`
            )
          )
        );
      }, timeoutMs);
      const cleanupListeners = () => {
        var _a;
        window.clearTimeout(timeoutId);
        if (frameFallbackId !== null) {
          window.clearTimeout(frameFallbackId);
          frameFallbackId = null;
        }
        if (frameCallbackId !== null) {
          (_a = video.cancelVideoFrameCallback) == null ? void 0 : _a.call(video, frameCallbackId);
          frameCallbackId = null;
        }
        video.removeEventListener("loadedmetadata", handleProgress);
        video.removeEventListener("loadeddata", handleProgress);
        video.removeEventListener("canplay", handleProgress);
        video.removeEventListener("playing", handleProgress);
        video.removeEventListener("resize", handleProgress);
        video.removeEventListener("error", handleError);
        track == null ? void 0 : track.removeEventListener("unmute", handleProgress);
        track == null ? void 0 : track.removeEventListener("ended", handleTrackEnded);
      };
      const finish = (callback) => {
        if (settled) {
          return;
        }
        settled = true;
        cleanupListeners();
        callback();
      };
      const resolveAfterFrame = () => {
        frameCallbackId = null;
        finish(resolve);
      };
      const handleProgress = () => {
        if (settled || frameCallbackId !== null || video.videoWidth <= 0 || video.videoHeight <= 0 || video.readyState < HTMLMediaElement.HAVE_CURRENT_DATA) {
          return;
        }
        if (video.requestVideoFrameCallback) {
          frameCallbackId = video.requestVideoFrameCallback(resolveAfterFrame);
          frameFallbackId = window.setTimeout(() => {
            frameFallbackId = null;
            finish(resolve);
          }, 500);
          return;
        }
        finish(resolve);
      };
      const handleError = () => {
        var _a;
        const mediaMessage = (_a = video.error) == null ? void 0 : _a.message;
        finish(
          () => reject(
            new Error(
              `${label}\u52A0\u8F7D\u5931\u8D25${mediaMessage ? `\uFF1A${mediaMessage}` : ""}`
            )
          )
        );
      };
      const handleTrackEnded = () => {
        finish(
          () => reject(new Error(`${label}\u8F68\u9053\u5DF2\u505C\u6B62`))
        );
      };
      video.addEventListener("loadedmetadata", handleProgress);
      video.addEventListener("loadeddata", handleProgress);
      video.addEventListener("canplay", handleProgress);
      video.addEventListener("playing", handleProgress);
      video.addEventListener("resize", handleProgress);
      video.addEventListener("error", handleError, { once: true });
      track == null ? void 0 : track.addEventListener("unmute", handleProgress);
      track == null ? void 0 : track.addEventListener("ended", handleTrackEnded, { once: true });
      void video.play().then(handleProgress).catch((error) => {
        playbackError = error;
        if (error instanceof DOMException && (error.name === "NotAllowedError" || error.name === "NotSupportedError")) {
          finish(() => reject(error));
        }
      });
      handleProgress();
    });
  }
  getSupportedMimeType() {
    var _a;
    const mp4Types = [
      "video/mp4",
      "video/mp4;codecs=avc1,mp4a.40.2",
      "video/mp4;codecs=h264,aac"
    ];
    const webmTypes = [
      "video/webm;codecs=vp9,opus",
      "video/webm;codecs=vp8,opus",
      "video/webm;codecs=vp9",
      "video/webm;codecs=vp8",
      "video/webm"
    ];
    const types = this.settings.videoFormat === "mp4" ? [...mp4Types, ...webmTypes] : [...webmTypes, ...mp4Types];
    return (_a = types.find((type) => MediaRecorder.isTypeSupported(type))) != null ? _a : "";
  }
  async cleanup() {
    var _a;
    this.stopDrawing();
    this.screenVideo.pause();
    this.cameraVideo.pause();
    this.screenVideo.srcObject = null;
    this.cameraVideo.srcObject = null;
    this.mediaHost.remove();
    (_a = this.nativeCameraBridge) == null ? void 0 : _a.dispose();
    this.nativeCameraBridge = null;
    this.stopStream(this.screenStream);
    this.stopStream(this.cameraStream);
    this.stopStream(this.microphoneStream);
    this.stopStream(this.composedStream);
    for (const source of this.audioSources) {
      source.disconnect();
    }
    this.audioSources = [];
    this.audioDestination = null;
    if (this.audioContext && this.audioContext.state !== "closed") {
      await this.audioContext.close().catch(() => void 0);
    }
    this.audioContext = null;
    if (this.mediaRecorder) {
      this.mediaRecorder.ondataavailable = null;
      this.mediaRecorder.onstop = null;
      this.mediaRecorder.onerror = null;
    }
    this.screenStream = null;
    this.cameraStream = null;
    this.microphoneStream = null;
    this.composedStream = null;
    this.mediaRecorder = null;
    this.recordedChunks = [];
    this.startedAt = 0;
    this.pausedAt = 0;
    this.totalPausedMs = 0;
  }
  stopStream(stream) {
    stream == null ? void 0 : stream.getTracks().forEach((track) => track.stop());
  }
  describeMediaError(error, fallback) {
    if (error instanceof DOMException) {
      if (error.name === "NotAllowedError" || error.name === "SecurityError") {
        return `${fallback}\uFF1A\u6743\u9650\u672A\u6388\u4E88`;
      }
      if (error.name === "NotFoundError" || error.name === "DevicesNotFoundError") {
        return `${fallback}\uFF1A\u672A\u627E\u5230\u8BBE\u5907`;
      }
      if (error.message) {
        return `${fallback}\uFF1A${error.message}`;
      }
    }
    if (error instanceof Error && error.message) {
      return `${fallback}\uFF1A${error.message}`;
    }
    return fallback;
  }
  describeUnknownError(error) {
    if (error instanceof Error) {
      return [error.name, error.message].filter(Boolean).join(": ");
    }
    return String(error);
  }
  clamp(value, min, max) {
    return Math.min(max, Math.max(min, value));
  }
  makeEven(value) {
    return Math.max(2, value - value % 2);
  }
  assertActive() {
    if (this.disposed) {
      throw new DOMException("\u5F55\u5236\u5DF2\u53D6\u6D88", "AbortError");
    }
  }
};

// src/recording-ui.ts
var import_obsidian2 = require("obsidian");
var RecordingOverlay = class {
  constructor(settings, callbacks) {
    this.cleanups = [];
    this.cameraAvailable = false;
    this.timerInterval = null;
    this.countdownTimer = null;
    this.countdownResolver = null;
    this.activeDragCleanup = null;
    this.destroyed = false;
    this.settings = settings;
    this.callbacks = callbacks;
    this.cameraPosition = {
      ...CAMERA_POSITION_COORDINATES[settings.cameraPosition]
    };
    this.cameraVisible = settings.enableCamera;
    this.controlsEl = document.body.createDiv({
      cls: "screen-recorder-controls is-preparing"
    });
    const dragButton = this.createIconButton(
      this.controlsEl,
      "grip-horizontal",
      "\u79FB\u52A8\u5F55\u5236\u63A7\u5236\u6761",
      "screen-recorder-drag-handle"
    );
    const timerGroup = this.controlsEl.createDiv({
      cls: "screen-recorder-timer"
    });
    this.statusDotEl = timerGroup.createSpan({
      cls: "screen-recorder-status-dot"
    });
    this.timerEl = timerGroup.createSpan({ text: "\u51C6\u5907\u4E2D" });
    this.pauseButton = this.createIconButton(
      this.controlsEl,
      "pause",
      "\u6682\u505C\u5F55\u5236"
    );
    this.pauseButton.disabled = true;
    this.cameraButton = this.createIconButton(
      this.controlsEl,
      "video",
      "\u9690\u85CF\u6444\u50CF\u5934"
    );
    this.cameraButton.disabled = true;
    this.stopButton = this.createIconButton(
      this.controlsEl,
      "square",
      "\u505C\u6B62\u5E76\u4FDD\u5B58",
      "screen-recorder-stop-button"
    );
    this.stopButton.disabled = true;
    this.cancelButton = this.createIconButton(
      this.controlsEl,
      "trash-2",
      "\u53D6\u6D88\u5E76\u4E22\u5F03",
      "screen-recorder-cancel-button"
    );
    this.countdownEl = document.body.createDiv({
      cls: "screen-recorder-countdown",
      attr: { "aria-live": "assertive" }
    });
    this.countdownEl.hide();
    this.cameraBubbleEl = document.body.createDiv({
      cls: `screen-recorder-camera-bubble is-${settings.cameraShape}`,
      attr: { "aria-label": "\u6444\u50CF\u5934\u9884\u89C8" }
    });
    this.cameraBubbleEl.style.setProperty(
      "--screen-recorder-camera-size",
      `${CAMERA_PREVIEW_SIZES[settings.cameraSize]}px`
    );
    this.cameraVideoEl = this.cameraBubbleEl.createEl("video", {
      cls: "screen-recorder-camera-video",
      attr: {
        autoplay: "",
        muted: "",
        playsinline: ""
      }
    });
    this.cameraVideoEl.muted = true;
    this.cameraBubbleEl.hide();
    this.listen(dragButton, "pointerdown", (event) => {
      this.startDraggingControls(event);
    });
    this.listen(this.cameraBubbleEl, "pointerdown", (event) => {
      this.startDraggingCamera(event);
    });
    this.listen(this.pauseButton, "click", () => {
      this.callbacks.onTogglePause();
    });
    this.listen(this.cameraButton, "click", () => {
      this.cameraVisible = !this.cameraVisible;
      this.updateCameraVisibility();
      this.callbacks.onToggleCamera(this.cameraVisible);
    });
    this.listen(this.stopButton, "click", () => {
      this.callbacks.onStop();
    });
    this.listen(this.cancelButton, "click", () => {
      if (this.countdownResolver) {
        this.finishCountdown(false);
      }
      this.callbacks.onCancel();
    });
    this.listen(window, "resize", () => {
      this.renderCameraPosition();
      this.keepControlsInViewport();
    });
    this.renderCameraPosition();
  }
  setCameraStream(stream) {
    this.cameraAvailable = Boolean(stream);
    this.cameraVisible = this.cameraVisible && this.cameraAvailable;
    this.cameraButton.disabled = !this.cameraAvailable;
    this.cameraVideoEl.srcObject = stream;
    if (stream) {
      void this.cameraVideoEl.play().catch(() => void 0);
    }
    this.updateCameraVisibility();
  }
  async runCountdown(seconds) {
    if (seconds <= 0) {
      return true;
    }
    this.countdownEl.show();
    let remaining = seconds;
    this.countdownEl.setText(String(remaining));
    return new Promise((resolve) => {
      this.countdownResolver = resolve;
      this.countdownTimer = window.setInterval(() => {
        remaining -= 1;
        if (remaining <= 0) {
          this.finishCountdown(true);
          return;
        }
        this.countdownEl.setText(String(remaining));
      }, 1e3);
    });
  }
  setRecording() {
    this.controlsEl.removeClass("is-preparing");
    this.controlsEl.addClass("is-recording");
    this.pauseButton.disabled = false;
    this.stopButton.disabled = false;
    this.cancelButton.disabled = false;
    this.startTimer();
    this.updateState();
  }
  updateState() {
    const status = this.callbacks.getStatus();
    const paused = status === "paused" /* Paused */;
    (0, import_obsidian2.setIcon)(this.pauseButton, paused ? "play" : "pause");
    this.pauseButton.setAttribute(
      "aria-label",
      paused ? "\u7EE7\u7EED\u5F55\u5236" : "\u6682\u505C\u5F55\u5236"
    );
    this.pauseButton.title = paused ? "\u7EE7\u7EED\u5F55\u5236" : "\u6682\u505C\u5F55\u5236";
    this.controlsEl.toggleClass("is-paused", paused);
    this.statusDotEl.toggleClass("is-paused", paused);
  }
  setFinalizing() {
    this.controlsEl.removeClass("is-recording", "is-paused");
    this.controlsEl.addClass("is-finalizing");
    this.timerEl.setText("\u4FDD\u5B58\u4E2D");
    this.pauseButton.disabled = true;
    this.cameraButton.disabled = true;
    this.stopButton.disabled = true;
    this.cancelButton.disabled = true;
    this.cameraBubbleEl.addClass("is-disabled");
    this.stopTimer();
  }
  destroy() {
    var _a;
    if (this.destroyed) return;
    this.destroyed = true;
    this.finishCountdown(false);
    this.stopTimer();
    (_a = this.activeDragCleanup) == null ? void 0 : _a.call(this);
    this.cleanups.splice(0).forEach((cleanup) => cleanup());
    this.cameraVideoEl.pause();
    this.cameraVideoEl.srcObject = null;
    this.controlsEl.remove();
    this.cameraBubbleEl.remove();
    this.countdownEl.remove();
  }
  createIconButton(parent, icon, label, className) {
    const button = parent.createEl("button", {
      cls: ["screen-recorder-icon-button", className].filter(Boolean).join(" "),
      attr: {
        type: "button",
        "aria-label": label,
        title: label
      }
    });
    (0, import_obsidian2.setIcon)(button, icon);
    return button;
  }
  startTimer() {
    this.stopTimer();
    const update = () => {
      this.timerEl.setText(
        this.formatDuration(this.callbacks.getElapsedMs())
      );
      this.updateState();
    };
    update();
    this.timerInterval = window.setInterval(update, 250);
  }
  stopTimer() {
    if (this.timerInterval !== null) {
      window.clearInterval(this.timerInterval);
      this.timerInterval = null;
    }
  }
  finishCountdown(completed) {
    if (this.countdownTimer !== null) {
      window.clearInterval(this.countdownTimer);
      this.countdownTimer = null;
    }
    this.countdownEl.hide();
    const resolver = this.countdownResolver;
    this.countdownResolver = null;
    resolver == null ? void 0 : resolver(completed);
  }
  updateCameraVisibility() {
    const visible = this.cameraVisible && this.cameraAvailable;
    this.cameraBubbleEl.toggle(visible);
    (0, import_obsidian2.setIcon)(this.cameraButton, visible ? "video" : "video-off");
    this.cameraButton.setAttribute(
      "aria-label",
      visible ? "\u9690\u85CF\u6444\u50CF\u5934" : "\u663E\u793A\u6444\u50CF\u5934"
    );
    this.cameraButton.title = visible ? "\u9690\u85CF\u6444\u50CF\u5934" : "\u663E\u793A\u6444\u50CF\u5934";
  }
  renderCameraPosition() {
    const margin = 24;
    const size = CAMERA_PREVIEW_SIZES[this.settings.cameraSize];
    const availableWidth = Math.max(0, window.innerWidth - size - margin * 2);
    const availableHeight = Math.max(
      0,
      window.innerHeight - size - margin * 2
    );
    this.cameraBubbleEl.style.left = `${margin + availableWidth * this.cameraPosition.x}px`;
    this.cameraBubbleEl.style.top = `${margin + availableHeight * this.cameraPosition.y}px`;
  }
  startDraggingCamera(event) {
    var _a;
    if (event.button !== 0 || this.cameraBubbleEl.hasClass("is-disabled")) {
      return;
    }
    event.preventDefault();
    const startRect = this.cameraBubbleEl.getBoundingClientRect();
    const offsetX = event.clientX - startRect.left;
    const offsetY = event.clientY - startRect.top;
    (_a = this.activeDragCleanup) == null ? void 0 : _a.call(this);
    this.cameraBubbleEl.addClass("is-dragging");
    const handleMove = (moveEvent) => {
      const margin = 12;
      const size = startRect.width;
      const maxLeft = Math.max(margin, window.innerWidth - size - margin);
      const maxTop = Math.max(margin, window.innerHeight - size - margin);
      const left = this.clamp(
        moveEvent.clientX - offsetX,
        margin,
        maxLeft
      );
      const top = this.clamp(
        moveEvent.clientY - offsetY,
        margin,
        maxTop
      );
      this.cameraBubbleEl.style.left = `${left}px`;
      this.cameraBubbleEl.style.top = `${top}px`;
      this.cameraPosition = {
        x: maxLeft === margin ? 0 : (left - margin) / (maxLeft - margin),
        y: maxTop === margin ? 0 : (top - margin) / (maxTop - margin)
      };
      this.callbacks.onCameraMove(this.cameraPosition);
    };
    const cleanup = () => {
      this.cameraBubbleEl.removeClass("is-dragging");
      window.removeEventListener("pointermove", handleMove);
      window.removeEventListener("pointerup", cleanup);
      if (this.activeDragCleanup === cleanup) {
        this.activeDragCleanup = null;
      }
    };
    window.addEventListener("pointermove", handleMove);
    window.addEventListener("pointerup", cleanup, { once: true });
    this.activeDragCleanup = cleanup;
  }
  startDraggingControls(event) {
    var _a;
    if (event.button !== 0) return;
    event.preventDefault();
    const rect = this.controlsEl.getBoundingClientRect();
    const offsetX = event.clientX - rect.left;
    const offsetY = event.clientY - rect.top;
    (_a = this.activeDragCleanup) == null ? void 0 : _a.call(this);
    this.controlsEl.style.left = `${rect.left}px`;
    this.controlsEl.style.top = `${rect.top}px`;
    this.controlsEl.style.bottom = "auto";
    this.controlsEl.style.transform = "none";
    this.controlsEl.addClass("is-dragging");
    const handleMove = (moveEvent) => {
      const margin = 8;
      const maxLeft = Math.max(
        margin,
        window.innerWidth - rect.width - margin
      );
      const maxTop = Math.max(
        margin,
        window.innerHeight - rect.height - margin
      );
      this.controlsEl.style.left = `${this.clamp(
        moveEvent.clientX - offsetX,
        margin,
        maxLeft
      )}px`;
      this.controlsEl.style.top = `${this.clamp(
        moveEvent.clientY - offsetY,
        margin,
        maxTop
      )}px`;
    };
    const cleanup = () => {
      this.controlsEl.removeClass("is-dragging");
      window.removeEventListener("pointermove", handleMove);
      window.removeEventListener("pointerup", cleanup);
      if (this.activeDragCleanup === cleanup) {
        this.activeDragCleanup = null;
      }
    };
    window.addEventListener("pointermove", handleMove);
    window.addEventListener("pointerup", cleanup, { once: true });
    this.activeDragCleanup = cleanup;
  }
  keepControlsInViewport() {
    const rect = this.controlsEl.getBoundingClientRect();
    if (!this.controlsEl.style.top) {
      return;
    }
    this.controlsEl.style.left = `${this.clamp(
      rect.left,
      8,
      Math.max(8, window.innerWidth - rect.width - 8)
    )}px`;
    this.controlsEl.style.top = `${this.clamp(
      rect.top,
      8,
      Math.max(8, window.innerHeight - rect.height - 8)
    )}px`;
  }
  listen(target, type, handler) {
    target.addEventListener(type, handler);
    this.cleanups.push(() => target.removeEventListener(type, handler));
  }
  formatDuration(milliseconds) {
    const totalSeconds = Math.floor(milliseconds / 1e3);
    const hours = Math.floor(totalSeconds / 3600);
    const minutes = Math.floor(totalSeconds % 3600 / 60);
    const seconds = totalSeconds % 60;
    return [hours, minutes, seconds].map((part) => String(part).padStart(2, "0")).join(":");
  }
  clamp(value, min, max) {
    return Math.min(max, Math.max(min, value));
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");
var ScreenRecorderSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("screen-recorder-settings");
    containerEl.createEl("h2", { text: "\u5F55\u5236\u5DE5\u4F5C\u53F0" });
    containerEl.createEl("h3", { text: "\u89C6\u9891" });
    new import_obsidian3.Setting(containerEl).setName("\u8F93\u51FA\u683C\u5F0F").setDesc("\u4F18\u5148\u4F7F\u7528\u6240\u9009\u683C\u5F0F\uFF1B\u8FD0\u884C\u73AF\u5883\u4E0D\u652F\u6301\u65F6\u81EA\u52A8\u56DE\u9000").addDropdown(
      (dropdown) => dropdown.addOption("mp4", "MP4 \xB7 H.264 / AAC").addOption("webm", "WebM \xB7 VP9 / Opus").setValue(this.plugin.settings.videoFormat).onChange(async (value) => {
        this.plugin.settings.videoFormat = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u89C6\u9891\u8D28\u91CF").setDesc("\u9650\u5236\u8F93\u51FA\u5206\u8FA8\u7387\u548C\u7801\u7387").addDropdown(
      (dropdown) => dropdown.addOption("high", "\u9AD8 \xB7 \u6700\u9AD8 2560 px").addOption("medium", "\u4E2D \xB7 \u6700\u9AD8 1920 px").addOption("low", "\u4F4E \xB7 \u6700\u9AD8 1280 px").setValue(this.plugin.settings.videoQuality).onChange(async (value) => {
        this.plugin.settings.videoQuality = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u5E27\u7387").setDesc("\u8F83\u9AD8\u5E27\u7387\u4F1A\u589E\u52A0 CPU \u548C\u6587\u4EF6\u5360\u7528").addDropdown(
      (dropdown) => dropdown.addOption("24", "24 FPS").addOption("30", "30 FPS").addOption("60", "60 FPS").setValue(String(this.plugin.settings.frameRate)).onChange(async (value) => {
        this.plugin.settings.frameRate = Number(
          value
        );
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u663E\u793A\u9F20\u6807").setDesc("\u8BF7\u6C42\u5171\u4EAB\u6E90\u5728\u5F55\u5236\u4E2D\u5305\u542B\u9F20\u6807\u6307\u9488").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showCursor).onChange(async (value) => {
        this.plugin.settings.showCursor = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u6444\u50CF\u5934" });
    new import_obsidian3.Setting(containerEl).setName("\u542F\u7528\u6444\u50CF\u5934").setDesc("\u5728\u5F55\u5236\u753B\u9762\u4E2D\u53E0\u52A0\u53EF\u62D6\u52A8\u7684\u6444\u50CF\u5934\u6C14\u6CE1").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableCamera).onChange(async (value) => {
        this.plugin.settings.enableCamera = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.enableCamera) {
      new import_obsidian3.Setting(containerEl).setName("\u6C14\u6CE1\u5927\u5C0F").addDropdown(
        (dropdown) => dropdown.addOption("small", "\u5C0F").addOption("medium", "\u4E2D").addOption("large", "\u5927").setValue(this.plugin.settings.cameraSize).onChange(async (value) => {
          this.plugin.settings.cameraSize = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian3.Setting(containerEl).setName("\u6C14\u6CE1\u5F62\u72B6").addDropdown(
        (dropdown) => dropdown.addOption("circle", "\u5706\u5F62").addOption("rounded", "\u5706\u89D2\u65B9\u5F62").setValue(this.plugin.settings.cameraShape).onChange(async (value) => {
          this.plugin.settings.cameraShape = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian3.Setting(containerEl).setName("\u9ED8\u8BA4\u4F4D\u7F6E").setDesc("\u5F55\u5236\u65F6\u53EF\u76F4\u63A5\u62D6\u52A8\u6444\u50CF\u5934\u6C14\u6CE1").addDropdown(
        (dropdown) => dropdown.addOption("top-left", "\u5DE6\u4E0A\u89D2").addOption("top-right", "\u53F3\u4E0A\u89D2").addOption("bottom-left", "\u5DE6\u4E0B\u89D2").addOption("bottom-right", "\u53F3\u4E0B\u89D2").setValue(this.plugin.settings.cameraPosition).onChange(async (value) => {
          this.plugin.settings.cameraPosition = value;
          await this.plugin.saveSettings();
        })
      );
    }
    containerEl.createEl("h3", { text: "\u97F3\u9891" });
    new import_obsidian3.Setting(containerEl).setName("\u5F55\u5236\u9EA6\u514B\u98CE").setDesc("\u7528\u4E8E\u8BB2\u89E3\u65C1\u767D\uFF0C\u5E76\u542F\u7528\u56DE\u58F0\u6D88\u9664\u548C\u964D\u566A").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableMicrophone).onChange(async (value) => {
        this.plugin.settings.enableMicrophone = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u5F55\u5236\u7CFB\u7EDF\u97F3\u9891").setDesc("\u662F\u5426\u53EF\u7528\u53D6\u51B3\u4E8E\u5171\u4EAB\u6E90\u548C\u64CD\u4F5C\u7CFB\u7EDF").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableSystemAudio).onChange(async (value) => {
        this.plugin.settings.enableSystemAudio = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u5DE5\u4F5C\u6D41" });
    new import_obsidian3.Setting(containerEl).setName("\u5F00\u59CB\u5012\u8BA1\u65F6").addDropdown(
      (dropdown) => dropdown.addOption("0", "\u5173\u95ED").addOption("3", "3 \u79D2").addOption("5", "5 \u79D2").setValue(String(this.plugin.settings.countdownSeconds)).onChange(async (value) => {
        this.plugin.settings.countdownSeconds = Number(
          value
        );
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u4FDD\u5B58\u76EE\u5F55").setDesc("\u76F8\u5BF9\u4E8E\u5F53\u524D Vault \u6839\u76EE\u5F55").addText(
      (text) => text.setPlaceholder("recordings").setValue(this.plugin.settings.recordingsFolder).onChange(async (value) => {
        this.plugin.settings.recordingsFolder = value.trim() || "recordings";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u63D2\u5165\u5230\u7B14\u8BB0").setDesc("\u5B8C\u6210\u540E\u628A\u89C6\u9891\u5D4C\u5165\u5F55\u5236\u5F00\u59CB\u65F6\u7684\u7B14\u8BB0").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.insertRecordingLink).onChange(async (value) => {
        this.plugin.settings.insertRecordingLink = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var ScreenRecorderPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.recorder = null;
    this.overlay = null;
    this.statusBarItem = null;
    this.ribbonButton = null;
    this.recordingTargetFile = null;
    this.isFinalizing = false;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "start-recording",
      name: "\u5F00\u59CB\u5C4F\u5E55\u548C\u6444\u50CF\u5934\u5F55\u5236",
      checkCallback: (checking) => {
        if (this.getStatus() !== "idle" /* Idle */) {
          return false;
        }
        if (!checking) {
          void this.startRecording();
        }
        return true;
      }
    });
    this.addCommand({
      id: "pause-recording",
      name: "\u6682\u505C\u5F55\u5236",
      checkCallback: (checking) => {
        if (this.getStatus() !== "recording" /* Recording */) {
          return false;
        }
        if (!checking) {
          this.togglePause();
        }
        return true;
      }
    });
    this.addCommand({
      id: "resume-recording",
      name: "\u7EE7\u7EED\u5F55\u5236",
      checkCallback: (checking) => {
        if (this.getStatus() !== "paused" /* Paused */) {
          return false;
        }
        if (!checking) {
          this.togglePause();
        }
        return true;
      }
    });
    this.addCommand({
      id: "stop-recording",
      name: "\u505C\u6B62\u5F55\u5236\u5E76\u4FDD\u5B58",
      checkCallback: (checking) => {
        const status = this.getStatus();
        if (status !== "recording" /* Recording */ && status !== "paused" /* Paused */) {
          return false;
        }
        if (!checking) {
          void this.stopRecording();
        }
        return true;
      }
    });
    this.addCommand({
      id: "cancel-recording",
      name: "\u53D6\u6D88\u5F55\u5236\u5E76\u4E22\u5F03",
      checkCallback: (checking) => {
        const status = this.getStatus();
        if (status === "idle" /* Idle */ || this.isFinalizing) {
          return false;
        }
        if (!checking) {
          void this.cancelRecording();
        }
        return true;
      }
    });
    this.ribbonButton = this.addRibbonIcon(
      "circle-dot",
      "\u5F00\u59CB\u5F55\u5236",
      () => {
        void this.handlePrimaryAction();
      }
    );
    this.ribbonButton.addClass("screen-recorder-ribbon-button");
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass("screen-recorder-status");
    this.registerDomEvent(this.statusBarItem, "click", () => {
      void this.handlePrimaryAction();
    });
    this.registerInterval(
      window.setInterval(() => this.updateAppChrome(), 500)
    );
    this.addSettingTab(new ScreenRecorderSettingTab(this.app, this));
    this.updateAppChrome();
  }
  onunload() {
    var _a, _b;
    (_a = this.overlay) == null ? void 0 : _a.destroy();
    this.overlay = null;
    (_b = this.recorder) == null ? void 0 : _b.dispose();
    this.recorder = null;
  }
  async startRecording() {
    var _a;
    if (this.getStatus() !== "idle" /* Idle */ || this.isFinalizing) {
      return;
    }
    try {
      this.getRecordingsFolder();
    } catch (error) {
      new import_obsidian4.Notice(`\u65E0\u6CD5\u5F00\u59CB\u5F55\u5236\uFF1A${this.describeError(error)}`, 7e3);
      return;
    }
    const activeFile = this.app.workspace.getActiveFile();
    this.recordingTargetFile = activeFile instanceof import_obsidian4.TFile ? activeFile : null;
    const recorder = new ScreenCameraRecorder(
      this.app,
      this.settings,
      {
        onDisplayEnded: () => {
          const status = this.getStatus();
          if (status === "starting" /* Starting */) {
            new import_obsidian4.Notice("\u5C4F\u5E55\u5171\u4EAB\u5DF2\u7ED3\u675F\uFF0C\u5F55\u5236\u5DF2\u53D6\u6D88");
            void this.cancelRecording(false);
          } else if (status === "recording" /* Recording */ || status === "paused" /* Paused */) {
            new import_obsidian4.Notice("\u5C4F\u5E55\u5171\u4EAB\u5DF2\u7ED3\u675F\uFF0C\u6B63\u5728\u4FDD\u5B58\u5F55\u5236");
            void this.stopRecording();
          }
        }
      },
      this.getNativeCameraAppPath()
    );
    this.recorder = recorder;
    this.updateAppChrome();
    try {
      const preparation = await recorder.prepare();
      if (this.recorder !== recorder || this.isFinalizing) {
        recorder.dispose();
        return;
      }
      this.overlay = new RecordingOverlay(this.settings, {
        onStop: () => void this.stopRecording(),
        onCancel: () => void this.cancelRecording(),
        onTogglePause: () => this.togglePause(),
        onToggleCamera: (visible) => {
          var _a2;
          return (_a2 = this.recorder) == null ? void 0 : _a2.setCameraVisible(visible);
        },
        onCameraMove: (position) => {
          var _a2;
          return (_a2 = this.recorder) == null ? void 0 : _a2.setCameraPosition(position);
        },
        getElapsedMs: () => {
          var _a2, _b;
          return (_b = (_a2 = this.recorder) == null ? void 0 : _a2.getElapsedMs()) != null ? _b : 0;
        },
        getStatus: () => this.getStatus()
      });
      this.overlay.setCameraStream(recorder.getCameraStream());
      for (const warning of preparation.warnings) {
        new import_obsidian4.Notice(warning, 6e3);
      }
      const shouldStart = await this.overlay.runCountdown(
        this.settings.countdownSeconds
      );
      if (!shouldStart || this.recorder !== recorder) {
        if (this.recorder === recorder) {
          await this.cancelRecording(false);
        }
        return;
      }
      recorder.beginRecording();
      this.overlay.setRecording();
      this.updateAppChrome();
      new import_obsidian4.Notice("\u5F55\u5236\u5DF2\u5F00\u59CB");
    } catch (error) {
      if (this.recorder !== recorder) {
        recorder.dispose();
        return;
      }
      console.error("Screen Recorder: failed to start", error);
      if (this.recorder === recorder) {
        recorder.dispose();
        this.recorder = null;
      }
      (_a = this.overlay) == null ? void 0 : _a.destroy();
      this.overlay = null;
      this.recordingTargetFile = null;
      this.updateAppChrome();
      new import_obsidian4.Notice(`\u5F55\u5236\u542F\u52A8\u5931\u8D25\uFF1A${this.describeError(error)}`, 7e3);
    }
  }
  togglePause() {
    var _a;
    if (!this.recorder || this.isFinalizing) {
      return;
    }
    if (this.recorder.getStatus() === "recording" /* Recording */) {
      this.recorder.pause();
    } else if (this.recorder.getStatus() === "paused" /* Paused */) {
      this.recorder.resume();
    } else {
      return;
    }
    (_a = this.overlay) == null ? void 0 : _a.updateState();
    this.updateAppChrome();
  }
  async stopRecording() {
    var _a, _b;
    if (!this.recorder || this.isFinalizing) {
      return;
    }
    const status = this.recorder.getStatus();
    if (status !== "recording" /* Recording */ && status !== "paused" /* Paused */) {
      return;
    }
    const recorder = this.recorder;
    this.isFinalizing = true;
    (_a = this.overlay) == null ? void 0 : _a.setFinalizing();
    this.updateAppChrome();
    try {
      const blob = await recorder.stopRecording();
      const filename = await this.saveRecording(blob);
      new import_obsidian4.Notice(`\u5F55\u5236\u5DF2\u4FDD\u5B58\u5230 ${filename}`, 6e3);
    } catch (error) {
      console.error("Screen Recorder: failed to stop or save", error);
      new import_obsidian4.Notice(`\u5F55\u5236\u4FDD\u5B58\u5931\u8D25\uFF1A${this.describeError(error)}`, 7e3);
    } finally {
      (_b = this.overlay) == null ? void 0 : _b.destroy();
      this.overlay = null;
      if (this.recorder === recorder) {
        this.recorder = null;
      }
      this.recordingTargetFile = null;
      this.isFinalizing = false;
      this.updateAppChrome();
    }
  }
  async cancelRecording(showNotice = true) {
    if (!this.recorder || this.isFinalizing) {
      return;
    }
    const recorder = this.recorder;
    this.isFinalizing = true;
    this.destroyOverlay();
    try {
      await recorder.cancelRecording();
      if (showNotice) {
        new import_obsidian4.Notice("\u5F55\u5236\u5DF2\u53D6\u6D88");
      }
    } finally {
      this.destroyOverlay();
      if (this.recorder === recorder) {
        this.recorder = null;
      }
      this.recordingTargetFile = null;
      this.isFinalizing = false;
      this.updateAppChrome();
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async handlePrimaryAction() {
    const status = this.getStatus();
    if (status === "idle" /* Idle */) {
      await this.startRecording();
      return;
    }
    if (status === "recording" /* Recording */ || status === "paused" /* Paused */) {
      await this.stopRecording();
    }
  }
  async saveRecording(blob) {
    const folder = this.getRecordingsFolder();
    await this.ensureFolderExists(folder);
    const extension = blob.type.startsWith("video/mp4") ? "mp4" : "webm";
    const timestamp = (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-");
    const basePath = (0, import_obsidian4.normalizePath)(
      `${folder}/recording-${timestamp}.${extension}`
    );
    const filename = this.getAvailablePath(basePath);
    await this.app.vault.createBinary(filename, await blob.arrayBuffer());
    if (this.settings.insertRecordingLink && this.recordingTargetFile) {
      try {
        await this.insertRecordingLink(
          filename,
          this.recordingTargetFile
        );
      } catch (error) {
        console.error(
          "Screen Recorder: recording saved but note insertion failed",
          error
        );
        new import_obsidian4.Notice(
          `\u89C6\u9891\u5DF2\u4FDD\u5B58\uFF0C\u4F46\u672A\u80FD\u63D2\u5165\u7B14\u8BB0\uFF1A${this.describeError(error)}`,
          7e3
        );
      }
    }
    return filename;
  }
  async insertRecordingLink(filename, targetFile) {
    var _a;
    const embed = `![[${filename}]]`;
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    if (((_a = activeView == null ? void 0 : activeView.file) == null ? void 0 : _a.path) === targetFile.path) {
      const cursor = activeView.editor.getCursor();
      activeView.editor.replaceRange(`
${embed}
`, cursor);
      return;
    }
    await this.app.vault.process(targetFile, (content) => {
      const separator = content.length === 0 || content.endsWith("\n") ? "" : "\n";
      return `${content}${separator}
${embed}
`;
    });
  }
  getNativeCameraAppPath() {
    const adapter = this.app.vault.adapter;
    if (adapter instanceof import_obsidian4.FileSystemAdapter && this.manifest.dir) {
      return (0, import_path.join)(
        adapter.getBasePath(),
        this.manifest.dir,
        "native",
        "CameraBridge.app"
      );
    }
    return (0, import_path.join)(__dirname, "native", "CameraBridge.app");
  }
  getRecordingsFolder() {
    const configured = this.settings.recordingsFolder.trim();
    const folder = (0, import_obsidian4.normalizePath)(configured || "recordings");
    if (folder === "/" || folder === "." || folder.startsWith("../") || folder.includes("/../")) {
      throw new Error("\u5F55\u5236\u76EE\u5F55\u5FC5\u987B\u4F4D\u4E8E\u5F53\u524D Vault \u5185");
    }
    return folder.replace(/\/+$/, "");
  }
  async ensureFolderExists(folderPath) {
    let current = "";
    for (const part of folderPath.split("/").filter(Boolean)) {
      current = current ? `${current}/${part}` : part;
      const existing = this.app.vault.getAbstractFileByPath(current);
      if (existing instanceof import_obsidian4.TFolder) {
        continue;
      }
      if (existing) {
        throw new Error(`${current} \u5DF2\u5B58\u5728\u4E14\u4E0D\u662F\u6587\u4EF6\u5939`);
      }
      await this.app.vault.createFolder(current);
    }
  }
  getAvailablePath(basePath) {
    if (!this.app.vault.getAbstractFileByPath(basePath)) {
      return basePath;
    }
    const dotIndex = basePath.lastIndexOf(".");
    const stem = dotIndex >= 0 ? basePath.slice(0, dotIndex) : basePath;
    const extension = dotIndex >= 0 ? basePath.slice(dotIndex) : "";
    let index = 2;
    let candidate = `${stem}-${index}${extension}`;
    while (this.app.vault.getAbstractFileByPath(candidate)) {
      index += 1;
      candidate = `${stem}-${index}${extension}`;
    }
    return candidate;
  }
  getStatus() {
    var _a, _b;
    return (_b = (_a = this.recorder) == null ? void 0 : _a.getStatus()) != null ? _b : "idle" /* Idle */;
  }
  destroyOverlay() {
    const overlay = this.overlay;
    this.overlay = null;
    overlay == null ? void 0 : overlay.destroy();
  }
  updateAppChrome() {
    var _a, _b, _c, _d;
    const status = this.getStatus();
    const isActive = status === "recording" /* Recording */ || status === "paused" /* Paused */;
    if (this.ribbonButton) {
      (0, import_obsidian4.setIcon)(this.ribbonButton, isActive ? "square" : "circle-dot");
      const label = isActive ? "\u505C\u6B62\u5F55\u5236\u5E76\u4FDD\u5B58" : "\u5F00\u59CB\u5F55\u5236";
      this.ribbonButton.setAttribute("aria-label", label);
      this.ribbonButton.setAttribute("data-tooltip-position", "right");
      this.ribbonButton.toggleClass("is-recording", isActive);
      this.ribbonButton.toggleClass(
        "is-paused",
        status === "paused" /* Paused */
      );
    }
    if (!this.statusBarItem) {
      return;
    }
    let text = "\u5F55\u5236";
    if (status === "starting" /* Starting */) {
      text = "\u51C6\u5907\u5F55\u5236";
    } else if (status === "recording" /* Recording */) {
      text = `\u5F55\u5236\u4E2D ${this.formatDuration(
        (_b = (_a = this.recorder) == null ? void 0 : _a.getElapsedMs()) != null ? _b : 0
      )}`;
    } else if (status === "paused" /* Paused */) {
      text = `\u5DF2\u6682\u505C ${this.formatDuration(
        (_d = (_c = this.recorder) == null ? void 0 : _c.getElapsedMs()) != null ? _d : 0
      )}`;
    } else if (status === "stopping" /* Stopping */ || this.isFinalizing) {
      text = "\u4FDD\u5B58\u5F55\u5236";
    }
    this.statusBarItem.setText(text);
    this.statusBarItem.toggleClass("is-recording", isActive);
    this.statusBarItem.toggleClass(
      "is-paused",
      status === "paused" /* Paused */
    );
  }
  async loadSettings() {
    const loaded = await this.loadData();
    const { enableAudio, ...currentSettings } = loaded != null ? loaded : {};
    const migrated = {
      ...DEFAULT_SETTINGS,
      ...currentSettings
    };
    if (typeof enableAudio === "boolean" && typeof (loaded == null ? void 0 : loaded.enableMicrophone) !== "boolean") {
      migrated.enableMicrophone = enableAudio;
    }
    if (typeof enableAudio === "boolean" && typeof (loaded == null ? void 0 : loaded.enableSystemAudio) !== "boolean") {
      migrated.enableSystemAudio = enableAudio;
    }
    this.settings = migrated;
  }
  describeError(error) {
    if (error instanceof DOMException) {
      if (error.name === "NotAllowedError" || error.name === "SecurityError") {
        return "\u6CA1\u6709\u83B7\u5F97\u5C4F\u5E55\u6216\u8BBE\u5907\u6743\u9650";
      }
      if (error.name === "NotFoundError") {
        return "\u6CA1\u6709\u627E\u5230\u53EF\u7528\u7684\u5F55\u5236\u8BBE\u5907";
      }
      if (error.name === "AbortError") {
        return "\u5C4F\u5E55\u9009\u62E9\u5DF2\u53D6\u6D88";
      }
      return error.message || error.name;
    }
    if (error instanceof Error) {
      return error.message;
    }
    return "\u672A\u77E5\u9519\u8BEF";
  }
  formatDuration(milliseconds) {
    const totalSeconds = Math.floor(milliseconds / 1e3);
    const minutes = Math.floor(totalSeconds / 60);
    const seconds = totalSeconds % 60;
    return `${String(minutes).padStart(2, "0")}:${String(seconds).padStart(
      2,
      "0"
    )}`;
  }
};
var main_default = ScreenRecorderPlugin;
